"""
Trust scorer — converts raw analyzer scores into a unified TrustScore.

Weighting (tunable via config in Phase 3):
  phishing       40%
  url_reputation 30%
  dark_patterns  20%
  keywords       10%

Score is inverted for phishing/dark_patterns/keywords (higher raw risk = lower trust).
url_reputation contributes positively.

Implemented in Phase 3.
"""
from __future__ import annotations
from app.services.analysis.engine import AnalysisResult


def compute_trust_score(result: AnalysisResult) -> dict:
    """
    Returns a dict matching the TrustScoreSchema shape.
    """
    score = (
        (100 - result.phishing_score) * 0.4 +
        result.url_reputation_score * 0.3 +
        (100 - result.dark_pattern_score) * 0.2 +
        (100 - result.keyword_risk_score) * 0.1
    )
    
    level = "safe"
    if score < 40:
        level = "critical"
    elif score < 60:
        level = "high"
    elif score < 80:
        level = "medium"
    elif score < 90:
        level = "low"
        
    return {
        "score": round(score, 1),
        "level": level,
        "dominant_category": "phishing" if result.phishing_score > 50 else None,
        "issues": result.detected_issues,
        "explanation": "Score generated by analysis engine heuristics.",
        "component_scores": {
            "phishing": result.phishing_score,
            "dark_patterns": result.dark_pattern_score,
            "url_reputation": result.url_reputation_score,
            "keyword_risk": result.keyword_risk_score,
        }
    }
